import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :you_congress, YouCongressWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
    "https://youcongress.org",
    "https://www.youcongress.org",
    "https://youcongress.com",
    "https://www.youcongress.com",
    "https://youcongress-production.fly.dev",
    "https://staging.youcongress.org"
  ]

config :anubis_mcp, :session_store,
  adapter: Anubis.Server.Session.Store.Redis,
  redis_url:
    System.get_env("UPSTASH_REDIS_REST_URL") || raise("UPSTASH_REDIS_REST_URL is missing"),
  pool_size: 10,
  # 30 minutes in milliseconds
  ttl: 1_800_000,
  namespace: "anubis:sessions",
  connection_name: :anubis_redis,
  # Optional Redix connection options
  redix_opts: []

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Swoosh.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
